[package]
name = "deca"
version = "0.0.4"
edition = "2018"
license = "MIT"
description = "CHIP-8 interpreter backend"
repository = "https://github.com/tobiasvl/deca"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.5"
itertools = "0.10"
